### ISSUE TITLE
Consulta var property

### ISSUE THREAD

**Issue by bmangia** [pdep-mit/ejemplos-de-clase-wollok#1]
Consulta, yo tengo una clase Nave y una clase **NaveDeCarga** que **hereda** de **nave**.

Si yo defino una variable, var property _velocidad_ en mi clase Nave, ¿Deberia ser capaz de llamarla con los getters y setters que me da property desde la clase NaveDeCarga?

@pdep-mit/aire

**Comment by mmatos** [comment]
Sí, si ves un warning de que no entienden el mensaje velocidad() o velocidad(valor) desestimalo, es una mejora pendiente a la inferencia de tipos de Wollok. Vas a ver que funciona al probarlo con los tests porque sí entienden esos mensajes.
