### ISSUE TITLE
Hago primer commit del trabajo entero, pero tengo un par de dudas

### ISSUE THREAD

**Issue by julchat** [pdep-mit/ejemplos-de-clase-wollok#2]
@pdep-mit/agua 
Hola, mientras hacia el ejercicio termine llegando a la necesidad de que necesitaba manejar mejor los errores, queria fijarme en el codigo de la clase pasada pero no lo encontre en la bitacora de esa clase. podrian subirlo o decir donde puedo ver lo de crear mis propios tipos de errores?

A lo que voy, en este caso yo quiero que solo entren por el catch las excepciones que surjan debido a que no se pudo cumplir algun objetivo, pero los anteriores si; y no los que correspondan a errores que nunca deberian pasar.
tambien quiero saber como era el assert ese en el que podias tomar un error y hacer que el test de bien si el tipo de error coincidia

gracias y saludos,
Cristian

> method cumplirMision(mision){
 		mision.validarQueNoEsteCumplida()
 		self.cumplirObjetivosDe(mision)
 	} 
 	method cumplirObjetivosDe(mision){
 		try{
 		mision.objetivosNoCumplidos().forEach{x=>self.queLoCumplaElQuePuede(x,mision)}
 		//si se llego abajo de este comentario, entonces recorrio exitosamente todos los objetivos sin chocarse con ningun error
 		mision.validarQueEsteCompleta() //por las dudas
 		const miembrosVivos = miembros.filter{x=>!(x.murio())}
 		miembrosVivos.forEach{x=>x.mejorar(mision.ultimaHabilidadRequerida())}
 		}catch error  {
 			//aca solo se deberia llegar por el findOrElse de queLoCumplaElQuePuede(x,mision)
 			throw new Exception(message="No se completó la misión, pero se pudieron haber completado algunos objetivos")
 		}

>  	method queLoCumplaElQuePuede(objetivo,mision) {
 		miembros.findOrElse({x=>x.puedeUsarHabilidad(objetivo.habilidadRequerida())},{self.error("Se encontró un objetivo no cumplible por falta de habilidad")}).cumplirObjetivoDe(objetivo,mision,self)
 		}

**Comment by mmatos** [comment]
Hola @julchat abriste el issue en el repo incorrecto. Lo cierro y lo seguimos por otro lado.
